// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_B-HXrUmGZhExjRVB-8GxsskgRZeJQXo',
    appId: '1:676175619895:web:42badd48f3cf26e6975cb2',
    messagingSenderId: '676175619895',
    projectId: 'buildready-dc86c',
    authDomain: 'buildready-dc86c.firebaseapp.com',
    storageBucket: 'buildready-dc86c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzyVBXoaJ_5P5_fh-PlA14fAyI4tVSII',
    appId: '1:676175619895:android:60f107bd2be93dce975cb2',
    messagingSenderId: '676175619895',
    projectId: 'buildready-dc86c',
    storageBucket: 'buildready-dc86c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHgyb-eacWA3w6XoxesdFoq-k2bqG83jA',
    appId: '1:676175619895:ios:867c0ec79e906c3e975cb2',
    messagingSenderId: '676175619895',
    projectId: 'buildready-dc86c',
    storageBucket: 'buildready-dc86c.appspot.com',
    iosBundleId: 'com.example.buildReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHgyb-eacWA3w6XoxesdFoq-k2bqG83jA',
    appId: '1:676175619895:ios:445b50718ca4cf01975cb2',
    messagingSenderId: '676175619895',
    projectId: 'buildready-dc86c',
    storageBucket: 'buildready-dc86c.appspot.com',
    iosBundleId: 'com.example.buildReady.RunnerTests',
  );
}
